NDefines.NCamera.SYSTEM_SPACE_SCALE_MULT = 25.0
NDefines.NShip.FLEET_MOVE_MAX_DIST_SHIPS = 100.0
NDefines.NShip.FLEET_BASE_FORMATION_SCALE = 8.0
NDefines.NGraphics.RANDOM_HEIGHT_MIN = 0
NDefines.NGraphics.RANDOM_HEIGHT_MAX = 0